import "./globals.css";
import type { Metadata } from "next";
import { Locale, i18n } from "@/i18n.config";

import { Poppins } from "next/font/google";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import LanguageSwitcher from "@/components/LanguageSwitcher/LanguageSwitcher";

const font = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin-ext"],
});

export const metadata: Metadata = {
  title: "Odmor nikad bliže",
  description:
    "Zagrebačka županija je 'zelena oaza' grada Zagreba s čarobnom prirodom te bogatom kulturnom baštinom sa preko 50 izletišta i obiteljskih poljoprivrednih domaćinstava, te tri vinske ceste.Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: Locale };
}) {
  return (
    <html lang={params.lang}>
      <body className={font.className}>
        <Navbar
          params={{
            lang: params.lang,
          }}
        />
        <main>{children}</main>
        <LanguageSwitcher
          params={{
            lang: params.lang,
          }}
        />
        {/* <Footer
          params={{
            lang: params.lang,
          }}
        /> */}
      </body>
    </html>
  );
}
