// // import type { Metadata } from 'next'
// // import { Inter } from 'next/font/google'
// // import './globals.css'

// // const inter = Inter({ subsets: ['latin'] })

// // // export const metadata: Metadata = {
// // //   title: 'Create Next App',
// // //   description: 'Generated by create next app',
// // // }

// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import LocaleSwitcher from "@/components/locale-switcher";
// import { defaultLocale } from "@/middleware";

// const inter = Inter({ subsets: ["latin"] });

// export default function RootLayout({
//   children,
//   params,
// }: {
//   children: React.ReactNode;
//   params: { lang: string };
// }) {
//   return (
//     <html lang={params.lang ?? defaultLocale}>
//       <body>
//         <LocaleSwitcher  />
//         {children}
//       </body>
//     </html>
//   );
// }

import "./globals.css";
import type { Metadata } from "next";
import { Locale, i18n } from "@/i18n.config";

import { Poppins } from "next/font/google";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import LanguageSwitcher from "@/components/LanguageSwitcher/LanguageSwitcher";
const font = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: Locale };
}) {
  return (
    <html lang={params.lang}>
      <body className={font.className}>
       
        <Navbar
          // data={undefined}
          params={{
            lang: params.lang,
          }}
        />
        <main>{children}</main>
        <LanguageSwitcher params={{
            lang: params.lang,
          }}/>
        <Footer
          params={{
            lang: params.lang,
          }}
        />
      </body>
    </html>
  );
}
